---
title: "STAT380 Final Project"
author: Grace Rovinsky
format: pdf
---

1. Set the stage–explain the context you’re trying to learn something about. MUST ANSWER: Why is this important to you?

2. Explain the data provenance – Answer the Who, What, When, Where, Why, and How questions for the origin of the data. Include any additional information that would be useful in understanding the context in which the data are embedded.
"Drawing on 20+ published sources, Tori M. Hoehler et al. have compiled a dataset of 10,000+ measurements of metabolic rates of mammals, fish, birds, insects, tree saplings, bacteria, and other living organisms. The dataset includes several types of metabolic rates (primarily basal, field, and maximum), and a mix of individual-organism and species-average measurements."
https://www.pnas.org/doi/10.1073/pnas.2303764120
https://www.pnas.org/doi/10.1073/pnas.2303764120#supplementary-materials
https://en.wikipedia.org/wiki/Basal_metabolic_rate

3. Exploratory Data Analysis
make 3-4 visualizations

4. Use Machine Learning Algorithms
You must use at least one of each: a Regression-based algorithm (SLR/MLR, logistic regression), and a Non-Regression based algorithm (kNN, CART, random forests).
Using an Unsupervised Learning algorithm (clustering, PCA) is highly encouraged, but not required.
Each algorithm must be explained for a general audience.
All results should be explained.
Where appropriate, comparisons between methods should be discussed. This includes highlighting the strengths and weaknesses of the various approaches as well as when each is appropriate.

5. A discussion of what you’ve learned from your work about the context and recommendations for future work.

6. Author Contributions – list out who did what in the project.

7. References – Citation style is your choice, but all sources should be documented (both in text and in the References section). This includes where you got your data.

8. Code Appendix - Add comments
## Code Appendix
```{r}
## Load all necessary packages
library(readxl)
metabolic_data <- read_excel("~/Downloads/pnas.2303764120.sd01.xlsx", sheet = "Metabolic_Data")
```